eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    # 是否优先使用IP地址作为主机名的标识，默认为false
    prefer-ip-address: false
    # 客户端向服务端发送心跳（服务续约任务）的调用时间间隔，默认为30秒
    lease-renewal-interval-in-seconds: 30
    # 服务端在收到最后一次心跳之后的等待时间上限（服务时效的时间），默认为90秒
    lease-expiration-duration-in-seconds: 90
  client:
    # 开启健康检查（需要spring-boot-starter-actuator依赖）
    healthcheck:
      enable: true
    # 服务注册中心地址，多个地址用 , 隔开
    service-url:
      defaultZone: http://admin:123456@118.25.87.131:${eureka.port:20000}/eureka/
      #defaultZone: http://admin:123456@${eureka.host:localhost}:${eureka.port:20000}/eureka/
spring:
  # 服务名
  application:
    name: user-local
  cloud:
    loadbalancer:
      # 开启重试机制
      retry:
        enabled: true
server:
  port: 20001
