server:
  port: 20006
spring:
  application:
    name: admin-server
  security:
    user:
      name: "admin"
      password: "123456"

eureka:
  instance:
    #instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    #instance-id: ${spring.cloud.client.ip-address}:${server.port}
    # \u662F\u5426\u4F18\u5148\u4F7F\u7528IP\u5730\u5740\u4F5C\u4E3A\u4E3B\u673A\u540D\u7684\u6807\u8BC6\uFF0C\u9ED8\u8BA4\u4E3Afalse
    prefer-ip-address: true
    # \u5BA2\u6237\u7AEF\u5411\u670D\u52A1\u7AEF\u53D1\u9001\u5FC3\u8DF3\uFF08\u670D\u52A1\u7EED\u7EA6\u4EFB\u52A1\uFF09\u7684\u8C03\u7528\u65F6\u95F4\u95F4\u9694\uFF0C\u9ED8\u8BA4\u4E3A30\u79D2
    lease-renewal-interval-in-seconds: 30
    # \u670D\u52A1\u7AEF\u5728\u6536\u5230\u6700\u540E\u4E00\u6B21\u5FC3\u8DF3\u4E4B\u540E\u7684\u7B49\u5F85\u65F6\u95F4\u4E0A\u9650\uFF08\u670D\u52A1\u65F6\u6548\u7684\u65F6\u95F4\uFF09\uFF0C\u9ED8\u8BA4\u4E3A90\u79D2
    lease-expiration-duration-in-seconds: 90
    health-check-url-path: /actuator/health
    metadata-map:
      user.name: ${spring.security.user.name}
      user.password: ${spring.security.user.password}


  client:
    # \u670D\u52A1\u6CE8\u518C\u4E2D\u5FC3\u5730\u5740\uFF0C\u591A\u4E2A\u5730\u5740\u7528 , \u9694\u5F00
    service-url:
      defaultZone: http://admin:123456@${eureka.host:localhost}:${eureka.port:20000}/eureka/
    registryFetchIntervalSeconds: 5


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS


eureka_server: @mvnEurekaServer@
